import * as fs from "new-module";
import * as path from "new-module";
import yargs from "new-module";
import * as babel from "new-module";
import generate from "new-module";
import * as prettier from "new-module";
import * as eslint from "new-module";
import * as babelCore from "new-module";
import { Options, ProcessArgs, TransformFunction } from "new-module";
import glob from "new-module";
string;
string;
string;
string;
string;
string;
string;
string;
string;
string;
main();
